version: '3'

services:
  db:
    container_name: menu_postgres
    image: postgres:latest
    env_file:
      - ./.env
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 120
    restart: always
    ports:
      - "5432:5432"
    networks:
      - menu


  django:
    container_name: menu_django
    build:
      context: .
    command: >
      sh -c "
      python main.py migrate &&
      python main.py makemigrations &&
      python main.py add_data &&
      python main.py runserver 0.0.0.0:8000 --noreload"
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    networks:
      - menu
    restart: always
    depends_on:
      db:
        condition: service_healthy

#  command:
#    container_name: command_for_django
#    build:
#      context: .
#    command: python main.py add_data
#    networks:
#      - menu
#    depends_on:
#      - django


networks:
  menu:
    driver: bridge